/*

 MAP_SHOP_MAIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\gbtd\Font_Menu.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map_Shop_MainWidth 20
#define Map_Shop_MainHeight 18
#define Map_Shop_MainBank 0

#define Map_Shop_Main Map_Shop_MainPLN0
extern unsigned char Map_Shop_MainPLN0[];
extern unsigned char Map_Shop_MainPLN1[];

/* End of MAP_SHOP_MAIN.H */
