/*

 TILES_MAN_1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 11

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Man_1_h_INCLUDE
#define __Tiles_Man_1_h_INCLUDE

/* Bank of tiles. */
#define Tiles_Man_1Bank 0
/* Start of tile array. */
extern const unsigned char Tiles_Man_1BLK0[];
/* Start of tile array. */
extern const unsigned char Tiles_Man_1BLK1[];
/* Start of tile array. */
extern const unsigned char Tiles_Man_1BLK1[];

#endif

/* End of TILES_MAN_1.H */
